name: Publish Core JSR

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write # The OIDC ID token is used for authentication with JSR.
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true

      - name: Setup Deno
        uses: denoland/setup-deno@v2

      - name: Create semantic-release config
        working-directory: ./packages/core
        run: |
          cat > .releaserc.json << EOF
          {
            "branches": ["main"],
            "plugins": [
              "@semantic-release/commit-analyzer",
              "@semantic-release/release-notes-generator",
              "@semantic-release/changelog",
              ["@semantic-release/exec", {
                "prepareCmd": "jq '.version = \"\${nextRelease.version}\"' jsr.json > jsr.json.tmp && mv jsr.json.tmp jsr.json"
              }],
              ["@semantic-release/github", {
                "successComment": false,
                "failTitle": false
              }]
            ]
          }
          EOF

      - name: Run semantic-release with Deno
        working-directory: ./packages/core
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          deno run -A --allow-scripts=npm:canvas@2.11.2 npm:semantic-release \
            -p npm:@semantic-release/github \
            -p npm:@semantic-release/changelog \
            -p npm:@semantic-release/exec

      - name: Publish core package
        working-directory: ./packages/core
        run: deno publish
